// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  adminSidebar: [
    {
      type: 'category',
      label: '📘 CMP Overview',
      collapsible: true,
      collapsed: false,
      items: [
        'overview/what-is-cmp',
        'overview/supported-orchestrators',
        'overview/architecture-overview',
        'overview/glossary',
      ],
    },
    {
      type: 'category',
      label: '🔌 Orchestrator Setup',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '☁️ CloudStack (ACS)',
          collapsible: true,
          collapsed: true,
          items: [
            'orchestrators/cloudstack/index',
            'orchestrators/cloudstack/connecting',
            'orchestrators/cloudstack/zones',
            {
              type: 'category',
              label: 'Templates',
              items: [
                'orchestrators/cloudstack/templates/index',
                'orchestrators/cloudstack/templates/preparing-cmp-compatible-templates',
                'orchestrators/cloudstack/templates/configuring-templates-at-cmp',
              ],
            },
            {
              type: 'category',
              label: 'CloudStack Packages',
              items: [
                'orchestrators/cloudstack/offering-sync-and-packages/index',                
                'orchestrators/cloudstack/offering-sync-and-packages/virtual-machine',
                'orchestrators/cloudstack/offering-sync-and-packages/virtual-router-vpc',
                'orchestrators/cloudstack/offering-sync-and-packages/load-balancer',
                'orchestrators/cloudstack/offering-sync-and-packages/kubernetes',
                'orchestrators/cloudstack/offering-sync-and-packages/ip-address',
                'orchestrators/cloudstack/offering-sync-and-packages/vm-autoscale',
                'orchestrators/cloudstack/offering-sync-and-packages/volumes',
                'orchestrators/cloudstack/offering-sync-and-packages/volumes-snapshot',
                'orchestrators/cloudstack/offering-sync-and-packages/template',
                'orchestrators/cloudstack/offering-sync-and-packages/iso',
                'orchestrators/cloudstack/offering-sync-and-packages/vm-backup',
                'orchestrators/cloudstack/offering-sync-and-packages/unit-pricing',
                'orchestrators/cloudstack/offering-sync-and-packages/products',
              ],
            },
            'orchestrators/cloudstack/client-registration',
            'orchestrators/cloudstack/console-proxy',
            'orchestrators/cloudstack/quota-management',
            'orchestrators/cloudstack/storage-settings',
            'orchestrators/cloudstack/snapshot-backup',
            'orchestrators/cloudstack/native-backup',
          ],
        },
        'orchestrators/openstack/index',
        'orchestrators/vmware/index',
        'orchestrators/proxmox/index',
        'orchestrators/opennebula/index',
        'orchestrators/ceph/index',
        'orchestrators/powerdns/index',
      ],
    },
    {
      type: 'category',
      label: 'Rate Cards',
      collapsible: true,
      collapsed: true,
      items: [
        'rate-cards/index',
        'rate-cards/pricing-formulas',
      ],
    },
    {
      type: 'category',
      label: '💰 Billing & Invoicing',
      collapsible: true,
      collapsed: true,
      items: [
        'billing/overview',
        {
          type: 'category',
          label: 'Payment Modes',
          collapsible: true,
          collapsed: true,
          items: [
            'billing/payment-modes/index',
            'billing/payment-modes/prepaid',
            'billing/payment-modes/postpaid',
            'billing/payment-modes/manual',
          ],
        },
        {
          type: 'category',
          label: 'Billing Cycles',
          collapsible: true,
          collapsed: true,
          items: [
            'billing/billing-cycles/index',
            'billing/billing-cycles/hourly',
            'billing/billing-cycles/monthly',
            'billing/billing-cycles/quarterly',
            'billing/billing-cycles/semi-annually',
            'billing/billing-cycles/annually',
            'billing/billing-cycles/bi-annually',
            'billing/billing-cycles/tri-annually',
          ],
        },
        {
          type: 'category',
          label: 'Billing Rules',
          collapsible: true,
          collapsed: true,
          items: [
            'billing/billing-rules/index',
            'billing/billing-rules/fixed-prorata',
            'billing/billing-rules/unfixed-prorata',
            'billing/billing-rules/date-to-date',
            'billing/billing-rules/fixed-calendar-month',
            'billing/billing-rules/unfixed-calendar-month',
          ],
        },
        {
          type: 'category',
          label: 'Payment Gateways',
          collapsible: true,
          collapsed: true,
          items: [
            'billing/payment-gateways/index',
            'billing/payment-gateways/stripe',
            'billing/payment-gateways/asiapay',
            'billing/payment-gateways/hyperpay',
            'billing/payment-gateways/authorize-net',
            'billing/payment-gateways/m-pesa',
            'billing/payment-gateways/paypal',
            'billing/payment-gateways/razorpay',
            'billing/payment-gateways/mollie',
            'billing/payment-gateways/dinger',
            'billing/payment-gateways/cardlink',
            'billing/payment-gateways/paytm',
            'billing/payment-gateways/payduniya',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '📊 Quota Management',
      collapsible: true,
      collapsed: true,
      items: [
        'quota/global-quotas',
        'quota/account-quotas',
        'quota/project-quotas',
        'quota/quota-requests',
        'quota/orchestrator-sync',
      ],
    },
    {
      type: 'category',
      label: '🔐 Authentication & SSO',
      collapsible: true,
      collapsed: true,
      items: [
        'auth/keycloak',
        'auth/2fa',
      ],
    },
    {
      type: 'category',
      label: '❓ FAQ & Troubleshooting',
      collapsible: true,
      collapsed: true,
      items: [
        'faq/billing',
        'faq/general',
      ],
    },
  ],
};

module.exports = sidebars;
