// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  adminSidebar: [
    {
      type: 'category',
      label: '📘 CMP Overview',
      collapsible: true,
      collapsed: false,
      items: [
        'overview/what-is-cmp',
        'overview/supported-orchestrators',
        'overview/backup-and-recovery',
        'overview/architecture-overview',
        'overview/glossary',
      ],
    },
    {
      type: 'category',
      label: 'Installation & Setup',
      collapsible: true,
      collapsed: true,
      items: [
        'installation/hosting-topology',
        'installation/prerequisites',
        {
          type: 'category',
          label: 'Orchestrator Requirements',
          collapsible: true,
          collapsed: true,
          items: [
            'installation/orchestrator-requirements/index',
            'installation/orchestrator-requirements/cloudstack',
            'installation/orchestrator-requirements/vmware',
            'installation/orchestrator-requirements/openstack',
            'installation/orchestrator-requirements/proxmox',
            'installation/orchestrator-requirements/ceph',
            'installation/orchestrator-requirements/impossible-cloud',
            'installation/orchestrator-requirements/veeam',
            'installation/orchestrator-requirements/powerdns',
            'installation/orchestrator-requirements/keycloak',
            'installation/orchestrator-requirements/digio',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '🔌 Orchestrator Setup',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '☁️ CloudStack (ACS)',
          collapsible: true,
          collapsed: true,
          items: [
            'orchestrators/cloudstack/index',
            'orchestrators/cloudstack/connecting',
            'orchestrators/cloudstack/zones',
            {
              type: 'category',
              label: 'Templates',
              items: [
                'orchestrators/cloudstack/templates/index',
                'orchestrators/cloudstack/templates/preparing-cmp-compatible-templates',
                'orchestrators/cloudstack/templates/configuring-templates-at-cmp',
              ],
            },
            {
              type: 'category',
              label: 'CloudStack Packages',
              items: [
                'orchestrators/cloudstack/offering-sync-and-packages/index',                
                'orchestrators/cloudstack/offering-sync-and-packages/virtual-machine',
                'orchestrators/cloudstack/offering-sync-and-packages/virtual-router-vpc',
                'orchestrators/cloudstack/offering-sync-and-packages/networks',
                'orchestrators/cloudstack/offering-sync-and-packages/load-balancer',
                'orchestrators/cloudstack/offering-sync-and-packages/kubernetes',
                {
                  type: 'category',
                  label: 'IP Address',
                  collapsible: true,
                  collapsed: true,
                  items: [
                    'orchestrators/cloudstack/offering-sync-and-packages/ip-address/index',
                    'orchestrators/cloudstack/offering-sync-and-packages/ip-address/packages',
                    'orchestrators/cloudstack/offering-sync-and-packages/ip-address/shared-network-ip-billing',
                  ],
                },
                'orchestrators/cloudstack/offering-sync-and-packages/vm-autoscale',
                'orchestrators/cloudstack/offering-sync-and-packages/volumes',
                'orchestrators/cloudstack/offering-sync-and-packages/volumes-snapshot',
                'orchestrators/cloudstack/offering-sync-and-packages/template',
                {
                  type: 'category',
                  label: 'ISO',
                  collapsible: true,
                  collapsed: true,
                  items: [
                    'orchestrators/cloudstack/offering-sync-and-packages/iso/index',
                    'orchestrators/cloudstack/offering-sync-and-packages/iso/prerequisites',
                    'orchestrators/cloudstack/offering-sync-and-packages/iso/packages',
                  ],
                },
                'orchestrators/cloudstack/offering-sync-and-packages/vm-backup',
                'orchestrators/cloudstack/offering-sync-and-packages/unit-pricing',
                'orchestrators/cloudstack/offering-sync-and-packages/products',
              ],
            },
            'orchestrators/cloudstack/client-registration',
            'orchestrators/cloudstack/console-proxy',
            'orchestrators/cloudstack/quota-management',
            'orchestrators/cloudstack/storage-settings',
          ],
        },
        {
          type: 'category',
          label: 'OpenStack',
          collapsible: true,
          collapsed: true,
          items: [
            'orchestrators/openstack/index',
            'orchestrators/openstack/connecting',
            'orchestrators/openstack/projects-and-credentials',
            'orchestrators/openstack/regions',
            {
              type: 'category',
              label: 'Images',
              items: [
                'orchestrators/openstack/images/index',
                'orchestrators/openstack/images/preparing-cmp-compatible-images',
                'orchestrators/openstack/images/configuring-images-at-cmp',
              ],
            },
            {
              type: 'category',
              label: 'OpenStack Packages',
              items: [
                'orchestrators/openstack/offering-sync-and-packages/index',
                'orchestrators/openstack/offering-sync-and-packages/virtual-machine',
                'orchestrators/openstack/offering-sync-and-packages/networks',
                'orchestrators/openstack/offering-sync-and-packages/load-balancer',
                'orchestrators/openstack/offering-sync-and-packages/kubernetes',
                'orchestrators/openstack/offering-sync-and-packages/ip-address',
                'orchestrators/openstack/offering-sync-and-packages/volumes',
                'orchestrators/openstack/offering-sync-and-packages/volumes-snapshot',
                'orchestrators/openstack/offering-sync-and-packages/image',
                'orchestrators/openstack/offering-sync-and-packages/unit-pricing',
                'orchestrators/openstack/offering-sync-and-packages/products',
              ],
            },
            'orchestrators/openstack/client-registration',
            'orchestrators/openstack/console',
            'orchestrators/openstack/quota-management',
            'orchestrators/openstack/storage-settings',
            'orchestrators/openstack/snapshot-backup',
          ],
        },
        'orchestrators/vmware/index',
        {
          type: 'category',
          label: 'Proxmox VE',
          collapsible: true,
          collapsed: true,
          items: [
            'orchestrators/proxmox/index',
            'orchestrators/proxmox/connecting',
            'orchestrators/proxmox/networks-and-ipam',
            {
              type: 'category',
              label: 'Templates',
              collapsible: true,
              collapsed: true,
              items: [
                'orchestrators/proxmox/templates/index',
                'orchestrators/proxmox/templates/preparing-cmp-compatible-templates',
              ],
            },
            {
              type: 'category',
              label: 'Proxmox Packages',
              collapsible: true,
              collapsed: true,
              items: [
                'orchestrators/proxmox/offering-sync-and-packages/index',
                'orchestrators/proxmox/offering-sync-and-packages/virtual-machine',
                'orchestrators/proxmox/offering-sync-and-packages/volumes',
                'orchestrators/proxmox/offering-sync-and-packages/vm-snapshot',
                {
                  type: 'category',
                  label: 'IP Address',
                  collapsible: true,
                  collapsed: true,
                  items: [
                    'orchestrators/proxmox/offering-sync-and-packages/ip-address/index',
                    'orchestrators/proxmox/offering-sync-and-packages/ip-address/packages',
                    'orchestrators/proxmox/offering-sync-and-packages/ip-address/shared-network-ip-billing',
                  ],
                },
                'orchestrators/proxmox/offering-sync-and-packages/unit-pricing',
              ],
            },
            'orchestrators/proxmox/node-selection-algorithm',
          ],
        },
        'orchestrators/opennebula/index',
        {
          type: 'category',
          label: 'CEPH (Object Storage)',
          collapsible: true,
          collapsed: true,
          items: [
            'orchestrators/ceph/index',
            'orchestrators/ceph/connecting',
            'orchestrators/ceph/packages',
          ],
        },
        {
          type: 'category',
          label: 'Impossible Cloud',
          collapsible: true,
          collapsed: true,
          items: [
            'orchestrators/impossible-cloud/index',
            'orchestrators/impossible-cloud/connecting',
            'orchestrators/impossible-cloud/packages',
          ],
        },
        {
          type: 'category',
          label: 'Veeam (VSPC)',
          collapsible: true,
          collapsed: true,
          items: [
            'orchestrators/veeam/index',
            'orchestrators/veeam/connecting',
            'orchestrators/veeam/packages',
          ],
        },
        {
          type: 'category',
          label: 'PowerDNS',
          collapsible: true,
          collapsed: true,
          items: [
            'orchestrators/powerdns/index',
            'orchestrators/powerdns/connecting',
            'orchestrators/powerdns/dns-pricing',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Orchestrator Features',
      collapsible: true,
      collapsed: true,
      items: [
        'orchestrator-features/index',
        {
          type: 'category',
          label: 'CloudStack (ACS)',
          collapsible: true,
          collapsed: true,
          items: [
            'orchestrator-features/cloudstack/index',
            {
              type: 'category',
              label: 'Virtual Machine',
              collapsible: true,
              collapsed: true,
              link: {
                type: 'doc',
                id: 'orchestrator-features/cloudstack/virtual-machine/index',
              },
              items: [
                'orchestrator-features/cloudstack/virtual-machine/vm-downgrade',
                'orchestrator-features/cloudstack/virtual-machine/monitoring',
              ],
            },
            'orchestrator-features/cloudstack/sync-resources',
            {
              type: 'category',
              label: 'Networks',
              collapsible: true,
              collapsed: true,
              items: [
                'orchestrator-features/cloudstack/networks/index',
                'orchestrator-features/cloudstack/networks/vpc-network',
                'orchestrator-features/cloudstack/networks/vpc-static-routes',
                {
                  type: 'category',
                  label: 'Remote Access VPN',
                  collapsible: true,
                  collapsed: true,
                  items: [
                    'orchestrator-features/cloudstack/networks/remote-access-vpn/index',
                    'orchestrator-features/cloudstack/networks/remote-access-vpn/workflow',
                    'orchestrator-features/cloudstack/networks/remote-access-vpn/vpn-users',
                    'orchestrator-features/cloudstack/networks/remote-access-vpn/limitations',
                  ],
                },
                {
                  type: 'category',
                  label: 'Site-to-Site VPN',
                  collapsible: true,
                  collapsed: true,
                  items: [
                    'orchestrator-features/cloudstack/networks/site-to-site-vpn/index',
                    'orchestrator-features/cloudstack/networks/site-to-site-vpn/vpn-gateway',
                    'orchestrator-features/cloudstack/networks/site-to-site-vpn/vpn-customer-gateway',
                    'orchestrator-features/cloudstack/networks/site-to-site-vpn/vpn-connection',
                  ],
                },
                'orchestrator-features/cloudstack/networks/isolated-network',
                'orchestrator-features/cloudstack/networks/l2-network',
                'orchestrator-features/cloudstack/networks/shared-network',
              ],
            },
            'orchestrator-features/cloudstack/volumes',
            'orchestrator-features/cloudstack/snapshots',
            {
              type: 'category',
              label: 'Backup',
              collapsible: true,
              collapsed: true,
              items: [
                'orchestrator-features/cloudstack/backup/index',
                'orchestrator-features/cloudstack/backup/automated-volume-snapshot-as-backup',
                'orchestrator-features/cloudstack/backup/cloudstack-br-based-backup',
                'orchestrator-features/cloudstack/backup/manage-backups',
                {
                  type: 'category',
                  label: 'Schedules',
                  collapsible: true,
                  collapsed: true,
                  items: [
                    'orchestrator-features/cloudstack/backup/schedules/index',
                    'orchestrator-features/cloudstack/backup/schedules/backup-schedules',
                    'orchestrator-features/cloudstack/backup/schedules/snapshot-schedules',
                  ],
                },
              ],
            },
            'orchestrator-features/cloudstack/load-balancers',
            {
              type: 'category',
              label: 'Kubernetes',
              collapsible: true,
              collapsed: true,
              items: [
                'orchestrator-features/cloudstack/kubernetes/index',
                'orchestrator-features/cloudstack/kubernetes/access-documents',
                'orchestrator-features/cloudstack/kubernetes/accessing-dashboard',
              ],
            },
            'orchestrator-features/cloudstack/ip-addresses',
            'orchestrator-features/cloudstack/bandwidth',
            {
              type: 'category',
              label: 'Autoscaling',
              collapsible: true,
              collapsed: true,
              items: [
                'orchestrator-features/cloudstack/autoscaling/index',
                'orchestrator-features/cloudstack/autoscaling/cloudstack-considerations',
                'orchestrator-features/cloudstack/autoscaling/create-at-cmp',
              ],
            },
            {
              type: 'category',
              label: 'Templates',
              collapsible: true,
              collapsed: true,
              items: [
                'orchestrator-features/cloudstack/templates/index',
                'orchestrator-features/cloudstack/templates/create-from-vm-root-volume',
              ],
            },
            'orchestrator-features/cloudstack/iso',
            'orchestrator-features/cloudstack/console-access',
          ],
        },
        {
          type: 'category',
          label: 'OpenStack',
          collapsible: true,
          collapsed: true,
          items: [
            'orchestrator-features/openstack/index',
            'orchestrator-features/openstack/public-networks',
            'orchestrator-features/openstack/bandwidth',
          ],
        },
        {
          type: 'category',
          label: 'VMware',
          collapsible: true,
          collapsed: true,
          items: ['orchestrator-features/vmware/index'],
        },
        {
          type: 'category',
          label: 'Proxmox VE',
          collapsible: true,
          collapsed: true,
          items: [
            'orchestrator-features/proxmox/index',
            'orchestrator-features/proxmox/networks',
            'orchestrator-features/proxmox/ipam',
            'orchestrator-features/proxmox/backup',
            'orchestrator-features/proxmox/roadmap',
          ],
        },
        {
          type: 'category',
          label: 'OpenNebula',
          collapsible: true,
          collapsed: true,
          items: ['orchestrator-features/opennebula/index'],
        },
        {
          type: 'category',
          label: 'CEPH',
          collapsible: true,
          collapsed: true,
          items: [
            'orchestrator-features/ceph/index',
            'orchestrator-features/ceph/object-storage',
            'orchestrator-features/ceph/buckets',
          ],
        },
        {
          type: 'category',
          label: 'Impossible Cloud',
          collapsible: true,
          collapsed: true,
          items: [
            'orchestrator-features/impossible-cloud/index',
            'orchestrator-features/impossible-cloud/object-storage',
            'orchestrator-features/impossible-cloud/buckets',
          ],
        },
        {
          type: 'category',
          label: 'Veeam',
          collapsible: true,
          collapsed: true,
          items: ['orchestrator-features/veeam/index'],
        },
        {
          type: 'category',
          label: 'PowerDNS',
          collapsible: true,
          collapsed: true,
          items: [
            'orchestrator-features/powerdns/index',
            'orchestrator-features/powerdns/dns-operations',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Platform Features',
      collapsible: true,
      collapsed: true,
      items: [
        'platform-features/index',
        'platform-features/apis',
        'platform-features/notifications',
        'platform-features/multi-language',
        'platform-features/auto-pay',
        {
          type: 'category',
          label: 'Customer Dashboard',
          collapsible: true,
          collapsed: true,
          items: [
            'platform-features/customer-dashboard/index',
            {
              type: 'category',
              label: 'Quota',
              collapsible: true,
              collapsed: true,
              items: [
                'platform-features/customer-dashboard/quota/quota-reports-and-usage-sync',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'StackAI (Beta)',
          collapsible: true,
          collapsed: true,
          items: [
            'platform-features/stackai/index',
            'platform-features/stackai/production-requirements',
            'platform-features/stackai/user-guide',
            'platform-features/stackai/roadmap',
          ],
        },
        {
          type: 'category',
          label: 'Global Settings',
          collapsible: true,
          collapsed: true,
          items: [
            'platform-features/global-settings/index',
            'platform-features/global-settings/enable-phone-input',
            'platform-features/global-settings/enable-mobile-verification',
            'platform-features/global-settings/enforce-mobile-verification',
            'platform-features/global-settings/hide-billing-phone',
            'platform-features/global-settings/hide-postal-code',
            'platform-features/global-settings/sanctum-token-expiration',
          ],
        },
        {
          type: 'category',
          label: 'CAPTCHA',
          collapsible: true,
          collapsed: true,
          items: [
            'platform-features/captcha/index',
            'platform-features/captcha/google-recaptcha-v2',
          ],
        },
        {
          type: 'category',
          label: 'SMS Gateways',
          collapsible: true,
          collapsed: true,
          items: [
            'platform-features/sms-gateways/index',
            'platform-features/sms-gateways/msg91',
            'platform-features/sms-gateways/twilio',
            'platform-features/sms-gateways/spinning-disk',
          ],
        },
        {
          type: 'category',
          label: 'Security',
          collapsible: true,
          collapsed: true,
          items: [
            'platform-features/security/index',
            'platform-features/security/user-enumeration',
            'platform-features/security/tickets-rate-limiting',
          ],
        },
        {
          type: 'category',
          label: 'Identity Providers',
          collapsible: true,
          collapsed: true,
          items: [
            'platform-features/identity-providers/keycloak',
            'platform-features/identity-providers/2fa',
            {
              type: 'category',
              label: 'Zitadel',
              collapsible: true,
              collapsed: true,
              items: [
                'platform-features/identity-providers/zitadel/index',
                'platform-features/identity-providers/zitadel/setup',
                'platform-features/identity-providers/zitadel/machine-user-and-pat',
                'platform-features/identity-providers/zitadel/user-migration',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Marketplace Apps',
          collapsible: true,
          collapsed: true,
          items: [
            'platform-features/marketplace-apps/index',
            'platform-features/marketplace-apps/configure-in-cmp',
            'platform-features/marketplace-apps/environment-variables',
            'platform-features/marketplace-apps/application-credentials',
            'platform-features/marketplace-apps/startup-script-limits',
            'platform-features/marketplace-apps/automation-limitations',
          ],
        },
        {
          type: 'category',
          label: 'Terms and Conditions',
          collapsible: true,
          collapsed: true,
          items: [
            'platform-features/terms-and-conditions/index',
            'platform-features/terms-and-conditions/one-liner',
            'platform-features/terms-and-conditions/in-step-form',
            'platform-features/terms-and-conditions/enforce',
          ],
        },
        {
          type: 'category',
          label: 'Store & Products',
          collapsible: true,
          collapsed: true,
          items: [
            'platform-features/store/index',
            'platform-features/store/categories',
            'platform-features/store/product-vendors',
            'platform-features/store/add-products',
            'platform-features/store/product-billing',
            'platform-features/store/orders',
            'platform-features/store/customer-store',
            'platform-features/store/billing-behavior',
            'platform-features/store/changelog',
          ],
        },
        {
          type: 'category',
          label: 'Reseller',
          collapsible: true,
          collapsed: true,
          items: [
            'platform-features/reseller/index',
            'platform-features/reseller/reseller-vs-vendor',
            'platform-features/reseller/reseller-billing',
          ],
        },
        {
          type: 'category',
          label: 'Affiliate',
          collapsible: true,
          collapsed: true,
          items: [
            'platform-features/affiliate/index',
            'platform-features/affiliate/registration',
            {
              type: 'category',
              label: 'Admin',
              collapsible: true,
              collapsed: true,
              items: [
                'platform-features/affiliate/admin/workflow',
                'platform-features/affiliate/admin/manage-affiliates',
                'platform-features/affiliate/admin/affiliate-details',
                'platform-features/affiliate/admin/program-commissions-payouts',
              ],
            },
            {
              type: 'category',
              label: 'Affiliate Dashboard',
              collapsible: true,
              collapsed: true,
              items: [
                'platform-features/affiliate/affiliate-dashboard/index',
                'platform-features/affiliate/affiliate-dashboard/dashboard',
                'platform-features/affiliate/affiliate-dashboard/referred-signups',
                'platform-features/affiliate/affiliate-dashboard/commissions',
                'platform-features/affiliate/affiliate-dashboard/payouts',
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '💰 Billing & Invoicing',
      collapsible: true,
      collapsed: true,
      items: [
        'billing/overview',
        'billing/billing-settings',
        'billing/one-account-one-invoice',
        {
          type: 'category',
          label: 'Customer Billing Dashboard',
          collapsible: true,
          collapsed: true,
          items: [
            'billing/customer-billing-dashboard/index',
            {
              type: 'category',
              label: 'Account Statement',
              collapsible: true,
              collapsed: true,
              items: [
                'billing/customer-billing-dashboard/account-statement/index',
                'billing/customer-billing-dashboard/account-statement/usage-details',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Rate Cards',
          collapsible: true,
          collapsed: true,
          items: [
            'billing/rate-cards/index',
            'billing/rate-cards/pricing-formulas',
          ],
        },
        'billing/stoppable-services',
        'billing/low-infra-credit-notifications',
        'billing/free-trials',
        {
          type: 'category',
          label: 'Invoice Settings',
          collapsible: true,
          collapsed: true,
          items: [
            'billing/invoice-settings/index',
            'billing/invoice-settings/branches',
            'billing/invoice-settings/invoice-details',
            'billing/invoice-settings/invoice-number',
            'billing/invoice-settings/taxation',
          ],
        },
        {
          type: 'category',
          label: 'Disciplinary Actions',
          collapsible: true,
          collapsed: true,
          items: [
            'billing/disciplinary-actions/index',
            'billing/disciplinary-actions/freeze',
            'billing/disciplinary-actions/suspend',
            'billing/disciplinary-actions/terminate',
          ],
        },
        {
          type: 'category',
          label: 'Payment Modes',
          collapsible: true,
          collapsed: true,
          items: [
            'billing/payment-modes/index',
            'billing/payment-modes/prepaid',
            'billing/payment-modes/postpaid',
            'billing/payment-modes/manual',
          ],
        },
        {
          type: 'category',
          label: 'Billing Cycles',
          collapsible: true,
          collapsed: true,
          items: [
            'billing/billing-cycles/index',
            'billing/billing-cycles/hourly',
            'billing/billing-cycles/monthly',
            'billing/billing-cycles/quarterly',
            'billing/billing-cycles/semi-annually',
            'billing/billing-cycles/annually',
            'billing/billing-cycles/bi-annually',
            'billing/billing-cycles/tri-annually',
          ],
        },
        {
          type: 'category',
          label: 'Billing Rules',
          collapsible: true,
          collapsed: true,
          items: [
            'billing/billing-rules/index',
            'billing/billing-rules/fixed-prorata',
            'billing/billing-rules/unfixed-prorata',
            'billing/billing-rules/date-to-date',
            'billing/billing-rules/fixed-calendar-month',
            'billing/billing-rules/unfixed-calendar-month',
          ],
        },
        {
          type: 'category',
          label: 'Payment Gateways',
          collapsible: true,
          collapsed: true,
          items: [
            'billing/payment-gateways/index',
            'billing/payment-gateways/new-gateway-requirements',
            'billing/payment-gateways/stripe',
            'billing/payment-gateways/asiapay',
            'billing/payment-gateways/hyperpay',
            'billing/payment-gateways/authorize-net',
            'billing/payment-gateways/m-pesa',
            'billing/payment-gateways/paypal',
            'billing/payment-gateways/razorpay',
            'billing/payment-gateways/mollie',
            'billing/payment-gateways/dinger',
            'billing/payment-gateways/cardlink',
            'billing/payment-gateways/paytm',
            'billing/payment-gateways/payduniya',
            'billing/payment-gateways/sslcommerz',
            'billing/payment-gateways/flutterwave',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '📊 Quota Management',
      collapsible: true,
      collapsed: true,
      items: [
        'quota/global-quotas',
        'quota/account-quotas',
        'quota/project-quotas',
        'quota/quota-requests',
        'quota/orchestrator-sync',
      ],
    },
    {
      type: 'category',
      label: '❓ FAQ & Q&A',
      collapsible: true,
      collapsed: true,
      items: [
        'faq/index',
        {
          type: 'category',
          label: 'Platform',
          collapsible: true,
          collapsed: true,
          items: [
            'faq/platform/index',
            'faq/platform/backup-architecture',
            'faq/platform/billing-pricing',
            'faq/platform/prepaid-coupons-credits',
            'faq/platform/ip-network-billing',
            'faq/platform/branding',
            'faq/platform/auth-2fa',
            'faq/platform/accounts-onboarding',
            'faq/platform/packages-storage',
            'faq/platform/settings',
          ],
        },
        {
          type: 'category',
          label: 'Orchestrators',
          collapsible: true,
          collapsed: true,
          items: [
            'faq/orchestrators/index',
            'faq/orchestrators/all-orchestrators',
            'faq/orchestrators/cloudstack',
            'faq/orchestrators/openstack',
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
