// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  adminSidebar: [
    {
      type: 'category',
      label: '📘 CMP Overview',
      collapsible: true,
      collapsed: false,
      items: [
        'overview/what-is-cmp',
        'overview/supported-orchestrators',
        'overview/architecture-overview',
        'overview/glossary',
        'overview/release-notes',
      ],
    },
    {
      type: 'category',
      label: '⚙️ Installation & Setup',
      collapsible: true,
      collapsed: true,
      items: [
        'installation/prerequisites',
        'installation/server-installation',
        'installation/domain-dns',
        'installation/ssl-tls',
        'installation/initial-setup',
        'installation/env-variables',
        {
          type: 'category',
          label: '📋 Orchestrator Requirements',
          collapsible: true,
          collapsed: true,
          items: [
            'installation/orchestrator-requirements/index',
            'installation/orchestrator-requirements/cloudstack',
            'installation/orchestrator-requirements/vmware',
            'installation/orchestrator-requirements/openstack',
            'installation/orchestrator-requirements/proxmox',
            'installation/orchestrator-requirements/ceph',
            'installation/orchestrator-requirements/powerdns',
            'installation/orchestrator-requirements/keycloak',
            'installation/orchestrator-requirements/digio',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '🔌 Orchestrator Setup',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '☁️ CloudStack (ACS)',
          collapsible: true,
          collapsed: true,
          items: [
            'orchestrators/cloudstack/index',
            'orchestrators/cloudstack/connecting',
            'orchestrators/cloudstack/zones',
            {
              type: 'category',
              label: 'Templates',
              items: [
                'orchestrators/cloudstack/templates/index',
                'orchestrators/cloudstack/templates/preparing-cmp-compatible-templates',
                'orchestrators/cloudstack/templates/configuring-templates-at-cmp',
              ],
            },
            {
              type: 'category',
              label: 'Offering Sync & Packages',
              items: [
                'orchestrators/cloudstack/offering-sync-and-packages/index',
                'orchestrators/cloudstack/offering-sync-and-packages/offering-sync',
                'orchestrators/cloudstack/offering-sync-and-packages/virtual-machine',
                'orchestrators/cloudstack/offering-sync-and-packages/virtual-router-vpc',
                'orchestrators/cloudstack/offering-sync-and-packages/load-balancer',
                'orchestrators/cloudstack/offering-sync-and-packages/kubernetes',
                'orchestrators/cloudstack/offering-sync-and-packages/ip-address',
                'orchestrators/cloudstack/offering-sync-and-packages/vm-autoscale',
                'orchestrators/cloudstack/offering-sync-and-packages/volumes',
                'orchestrators/cloudstack/offering-sync-and-packages/volumes-snapshot',
                'orchestrators/cloudstack/offering-sync-and-packages/template',
                'orchestrators/cloudstack/offering-sync-and-packages/iso',
                'orchestrators/cloudstack/offering-sync-and-packages/vm-backup',
                'orchestrators/cloudstack/offering-sync-and-packages/unit-pricing',
                'orchestrators/cloudstack/offering-sync-and-packages/products',
              ],
            },
            'orchestrators/cloudstack/client-registration',
            'orchestrators/cloudstack/console-proxy',
            'orchestrators/cloudstack/quota-management',
            'orchestrators/cloudstack/snapshot-backup',
            'orchestrators/cloudstack/native-backup',
          ],
        },
        'orchestrators/openstack/index',
        'orchestrators/vmware/index',
        'orchestrators/proxmox/index',
        'orchestrators/opennebula/index',
        'orchestrators/ceph/index',
        'orchestrators/powerdns/index',
      ],
    },
    {
      type: 'category',
      label: '📦 Packages & Offerings',
      collapsible: true,
      collapsed: true,
      items: [
        'packages/overview',
        'packages/vm-packages',
        'packages/custom-packages',
        'packages/block-storage',
        'packages/ip-addresses',
        'packages/lb-vpc-bandwidth',
        'packages/pricing-formulas',
      ],
    },
    {
      type: 'category',
      label: '💰 Billing & Invoicing',
      collapsible: true,
      collapsed: true,
      items: [
        'billing/overview',
        'billing/prepaid-wallet',
      ],
    },
    {
      type: 'category',
      label: '📊 Quota Management',
      collapsible: true,
      collapsed: true,
      items: [
        'quota/global-quotas',
        'quota/account-quotas',
        'quota/project-quotas',
        'quota/quota-requests',
        'quota/orchestrator-sync',
      ],
    },
    {
      type: 'category',
      label: '🔐 Authentication & SSO',
      collapsible: true,
      collapsed: true,
      items: [
        'auth/keycloak',
        'auth/2fa',
      ],
    },
    {
      type: 'category',
      label: '❓ FAQ & Troubleshooting',
      collapsible: true,
      collapsed: true,
      items: [
        'faq/billing',
        'faq/general',
      ],
    },
  ],
};

module.exports = sidebars;
