import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  adminSidebar: [
    {
      type: 'category',
      label: 'CMP Overview',
      collapsible: true,
      collapsed: false,
      items: [
        'overview/what-is-cmp',
        'overview/supported-orchestrators',
        'overview/architecture-overview',
        'overview/glossary',
      ],
    },
    {
      type: 'category',
      label: 'Orchestrator Setup',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'CloudStack (ACS)',
          collapsible: true,
          collapsed: true,
          items: [
            'orchestrators/cloudstack/index',
            'orchestrators/cloudstack/connecting',         
            'orchestrators/cloudstack/zones',   
            {
              type: 'category',
              label: 'Templates',
              items: [
                'orchestrators/cloudstack/templates/index',
                'orchestrators/cloudstack/templates/preparing-cmp-compatible-templates',
                'orchestrators/cloudstack/templates/configuring-templates-at-cmp',
              ],
            },
            {
              type: 'category',
              label: 'CloudStack Packages',
              items: [
                'orchestrators/cloudstack/offering-sync-and-packages/index',            
                'orchestrators/cloudstack/offering-sync-and-packages/virtual-machine',
                'orchestrators/cloudstack/offering-sync-and-packages/virtual-router-vpc',
                'orchestrators/cloudstack/offering-sync-and-packages/networks',
                'orchestrators/cloudstack/offering-sync-and-packages/load-balancer',
                'orchestrators/cloudstack/offering-sync-and-packages/kubernetes',
                'orchestrators/cloudstack/offering-sync-and-packages/ip-address',
                'orchestrators/cloudstack/offering-sync-and-packages/vm-autoscale',
                'orchestrators/cloudstack/offering-sync-and-packages/volumes',
                'orchestrators/cloudstack/offering-sync-and-packages/volumes-snapshot',
                'orchestrators/cloudstack/offering-sync-and-packages/template',
                'orchestrators/cloudstack/offering-sync-and-packages/iso',
                'orchestrators/cloudstack/offering-sync-and-packages/vm-backup',
                'orchestrators/cloudstack/offering-sync-and-packages/unit-pricing',
                'orchestrators/cloudstack/offering-sync-and-packages/products',
              ],
            },
            'orchestrators/cloudstack/client-registration',
            'orchestrators/cloudstack/console-proxy',
            'orchestrators/cloudstack/quota-management',
            'orchestrators/cloudstack/storage-settings',
            'orchestrators/cloudstack/snapshot-backup',
            'orchestrators/cloudstack/native-backup',
          ],
        },
        'orchestrators/openstack/index',
        'orchestrators/vmware/index',
        'orchestrators/proxmox/index',
        'orchestrators/opennebula/index',
        {
          type: 'category',
          label: 'CEPH (Object Storage)',
          collapsible: true,
          collapsed: true,
          items: [
            'orchestrators/ceph/index',
            'orchestrators/ceph/connecting',
            'orchestrators/ceph/packages',
          ],
        },
        'orchestrators/powerdns/index',
      ],
    },
    {
      type: 'category',
      label: 'Orchestrator Features',
      collapsible: true,
      collapsed: true,
      items: [
        'orchestrator-features/index',
        {
          type: 'category',
          label: 'CloudStack (ACS)',
          collapsible: true,
          collapsed: true,
          items: [
            'orchestrator-features/cloudstack/index',
            'orchestrator-features/cloudstack/virtual-machines',
            {
              type: 'category',
              label: 'Networks',
              collapsible: true,
              collapsed: true,
              items: [
                'orchestrator-features/cloudstack/networks/index',
                'orchestrator-features/cloudstack/networks/vpc-network',
                'orchestrator-features/cloudstack/networks/isolated-network',
                'orchestrator-features/cloudstack/networks/l2-network',
                'orchestrator-features/cloudstack/networks/shared-network',
              ],
            },
            'orchestrator-features/cloudstack/volumes',
            'orchestrator-features/cloudstack/snapshots',
            'orchestrator-features/cloudstack/vm-backup',
            'orchestrator-features/cloudstack/load-balancers',
            'orchestrator-features/cloudstack/kubernetes',
            'orchestrator-features/cloudstack/ip-addresses',
            'orchestrator-features/cloudstack/bandwidth',
            {
              type: 'category',
              label: 'Autoscaling',
              collapsible: true,
              collapsed: true,
              items: [
                'orchestrator-features/cloudstack/autoscaling/index',
                'orchestrator-features/cloudstack/autoscaling/cloudstack-considerations',
                'orchestrator-features/cloudstack/autoscaling/create-at-cmp',
              ],
            },
            {
              type: 'category',
              label: 'Templates',
              collapsible: true,
              collapsed: true,
              items: [
                'orchestrator-features/cloudstack/templates/index',
                'orchestrator-features/cloudstack/templates/create-from-vm-root-volume',
              ],
            },
            'orchestrator-features/cloudstack/iso',
            'orchestrator-features/cloudstack/console-access',
          ],
        },
        {
          type: 'category',
          label: 'OpenStack',
          collapsible: true,
          collapsed: true,
          items: [
            'orchestrator-features/openstack/index',
            'orchestrator-features/openstack/bandwidth',
          ],
        },
        {
          type: 'category',
          label: 'VMware',
          collapsible: true,
          collapsed: true,
          items: ['orchestrator-features/vmware/index'],
        },
        {
          type: 'category',
          label: 'Proxmox VE',
          collapsible: true,
          collapsed: true,
          items: ['orchestrator-features/proxmox/index'],
        },
        {
          type: 'category',
          label: 'OpenNebula',
          collapsible: true,
          collapsed: true,
          items: ['orchestrator-features/opennebula/index'],
        },
        {
          type: 'category',
          label: 'CEPH',
          collapsible: true,
          collapsed: true,
          items: [
            'orchestrator-features/ceph/index',
            'orchestrator-features/ceph/object-storage',
            'orchestrator-features/ceph/buckets',
          ],
        },
        {
          type: 'category',
          label: 'PowerDNS',
          collapsible: true,
          collapsed: true,
          items: ['orchestrator-features/powerdns/index'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Platform Features',
      collapsible: true,
      collapsed: true,
      items: [
        'platform-features/index',
        'platform-features/apis',
        'platform-features/notifications',
        'platform-features/store',
      ],
    },
    {
      type: 'category',
      label: 'Billing & Invoicing',
      collapsible: true,
      collapsed: true,
      items: [
        'billing/overview',
        {
          type: 'category',
          label: 'Rate Cards',
          collapsible: true,
          collapsed: true,
          items: [
            'billing/rate-cards/index',
            'billing/rate-cards/pricing-formulas',
          ],
        },
        'billing/stoppable-services',
        'billing/low-infra-credit-notifications',
        {
          type: 'category',
          label: 'Invoice Settings',
          collapsible: true,
          collapsed: true,
          items: [
            'billing/invoice-settings/index',
            'billing/invoice-settings/branches',
            'billing/invoice-settings/invoice-details',
            'billing/invoice-settings/invoice-number',
            'billing/invoice-settings/taxation',
            'billing/invoice-settings/terms-and-conditions',
          ],
        },
        {
          type: 'category',
          label: 'Disciplinary Actions',
          collapsible: true,
          collapsed: true,
          items: [
            'billing/disciplinary-actions/index',
            'billing/disciplinary-actions/freeze',
            'billing/disciplinary-actions/suspend',
            'billing/disciplinary-actions/terminate',
          ],
        },
        {
          type: 'category',
          label: 'Payment Modes',
          collapsible: true,
          collapsed: true,
          items: [
            'billing/payment-modes/index',
            'billing/payment-modes/prepaid',
            'billing/payment-modes/postpaid',
            'billing/payment-modes/manual',
          ],
        },
        {
          type: 'category',
          label: 'Billing Cycles',
          collapsible: true,
          collapsed: true,
          items: [
            'billing/billing-cycles/index',
            'billing/billing-cycles/hourly',
            'billing/billing-cycles/monthly',
            'billing/billing-cycles/quarterly',
            'billing/billing-cycles/semi-annually',
            'billing/billing-cycles/annually',
            'billing/billing-cycles/bi-annually',
            'billing/billing-cycles/tri-annually',
          ],
        },
        {
          type: 'category',
          label: 'Billing Rules',
          collapsible: true,
          collapsed: true,
          items: [
            'billing/billing-rules/index',
            'billing/billing-rules/fixed-prorata',
            'billing/billing-rules/unfixed-prorata',
            'billing/billing-rules/date-to-date',
            'billing/billing-rules/fixed-calendar-month',
            'billing/billing-rules/unfixed-calendar-month',
          ],
        },
        {
          type: 'category',
          label: 'Payment Gateways',
          collapsible: true,
          collapsed: true,
          items: [
            'billing/payment-gateways/index',
            'billing/payment-gateways/stripe',
            'billing/payment-gateways/asiapay',
            'billing/payment-gateways/hyperpay',
            'billing/payment-gateways/authorize-net',
            'billing/payment-gateways/m-pesa',
            'billing/payment-gateways/paypal',
            'billing/payment-gateways/razorpay',
            'billing/payment-gateways/mollie',
            'billing/payment-gateways/dinger',
            'billing/payment-gateways/cardlink',
            'billing/payment-gateways/paytm',
            'billing/payment-gateways/payduniya',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Quota Management',
      collapsible: true,
      collapsed: true,
      items: [
        'quota/global-quotas',
        'quota/account-quotas',
        'quota/project-quotas',
        'quota/quota-requests',
        'quota/orchestrator-sync',
      ],
    },
    {
      type: 'category',
      label: 'Authentication & SSO',
      collapsible: true,
      collapsed: true,
      items: [
        'auth/keycloak',
        'auth/2fa',
      ],
    },
    {
      type: 'category',
      label: 'FAQ & Q&A',
      collapsible: true,
      collapsed: true,
      items: [
        'faq/index',
        {
          type: 'category',
          label: 'Platform',
          collapsible: true,
          collapsed: true,
          items: [
            'faq/platform/index',
            'faq/platform/billing-pricing',
            'faq/platform/prepaid-coupons-credits',
            'faq/platform/ip-network-billing',
            'faq/platform/branding',
            'faq/platform/auth-2fa',
            'faq/platform/accounts-onboarding',
            'faq/platform/packages-storage',
            'faq/platform/settings',
          ],
        },
        {
          type: 'category',
          label: 'Orchestrators',
          collapsible: true,
          collapsed: true,
          items: [
            'faq/orchestrators/index',
            'faq/orchestrators/all-orchestrators',
            'faq/orchestrators/cloudstack',
            'faq/orchestrators/openstack',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
